### ISSUE TITLE
client cert tls support

### ISSUE THREAD

**Issue by glycerine** [nats-io/nats-top#23]
currently nats-top goes blind when client certs are in use. It would be great to be able to supply the certs and CA to nats-top so it can monitor a secured gnatsd.

**Comment by wallyqs** [comment]
Thanks for the feedback, have a branch now where I'm adding this.

**Comment by glycerine** [comment]
Great! Happy to try it in my setup when you are ready.

**Comment by wallyqs** [comment]
Thanks! Support for this is in master now.

**Comment by wallyqs** [comment]
Support for this included in latest release of the nats-top binary https://github.com/nats-io/nats-top/releases/tag/v0.2.0

**Comment by wallyqs** [comment]
Fixed via #24

**Comment by glycerine** [comment]
Excellent. Thanks @wallyqs !
