### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by proc** [nats-io/nats-top#25]
When running "go get" on the package, there are errors on build:

$ go get github.com/nats-io/nats-top
# github.com/nats-io/nats-top
github.com/nats-io/nats-top/nats-top.go:236: par.HasBorder undefined (type *termui.Par has no field or method HasBorder)
github.com/nats-io/nats-top/nats-top.go:242: helpPar.HasBorder undefined (type *termui.Par has no field or method HasBorder)
github.com/nats-io/nats-top/nats-top.go:293: undefined: termui.EventCh
github.com/nats-io/nats-top/nats-top.go:305: undefined: termui.EventKey
github.com/nats-io/nats-top/nats-top.go:305: undefined: termui.KeyEnter
github.com/nats-io/nats-top/nats-top.go:331: undefined: termui.EventKey
github.com/nats-io/nats-top/nats-top.go:331: undefined: termui.KeyBackspace
github.com/nats-io/nats-top/nats-top.go:331: undefined: termui.KeyBackspace2
github.com/nats-io/nats-top/nats-top.go:342: undefined: termui.EventKey
github.com/nats-io/nats-top/nats-top.go:342: undefined: termui.KeyEnter
github.com/nats-io/nats-top/nats-top.go:342: too many errors

**Comment by wallyqs** [comment]
will make a release of the binary as an alternative of `go get`... what platform are you on by the way?

**Comment by proc** [comment]
hi @wallyqs, I am running it on osx locally, but would also like to run it in our production environment (ec2 + linux).  Is this an osx specific problem?

**Comment by wallyqs** [comment]
Using it in OS X myself but have binaries of a previous release here too: 
- OS X: https://github.com/nats-io/nats-top/releases/download/v0.1.0/nats-top-v0-1-0-darwin-amd64.tar.gz
- Linux: https://github.com/nats-io/nats-top/releases/download/v0.1.0/nats-top-v0-1-0-linux-amd64.tar.gz
Let me know if either does not work for you

**Comment by wallyqs** [comment]
Released binaries including recent changes which can be fetched here as well: https://github.com/nats-io/nats-top/releases/tag/v0.2.0

**Comment by mcqueary** [comment]
@proc were you able to get this working?

**Comment by mcqueary** [comment]
Closing, as this seems to be an isolated incident and/or environmental in nature. @proc Please let us know if you're still having a problem.
