### ISSUE TITLE
User/Password

### ISSUE THREAD

**Issue by hphde** [nats-io/nats-top#36]
**gnatsd** allows to setup authorization. **nats-top** should be able to work with that

[gnatsd auth link](https://github.com/nats-io/gnatsd/tree/master/auth)

**Comment by wallyqs** [comment]
those are the creds to be able to connect to the nats-server, and nats-top just polls from the monitoring endpoint making `http` requests which for security could be setup to use `https` based polling instead, and that is supported :) https://github.com/nats-io/nats-top#usage

**Comment by emalovan** [comment]
My gnats is configured with user/password auth, but nats-top doesn't allow to type any user creds to poll the data, only cert (which I don't use at all). I believe the initial request was to let this work with user/pass auth. Thanks

**Comment by YoshieraHuang** [comment]
I configure one nats-server with token but i don't know how to provide the token to nats-top to connect.

**Comment by derekcollison** [comment]
nats-top uses the HTTP monitoring interface which does not have auth.

**Comment by YoshieraHuang** [comment]
> nats-top uses the HTTP monitoring interface which does not have auth.

I figure out from the log of nats docker container  that when i assign a token for auth the management service does not be set up。

**Comment by derekcollison** [comment]
NATS 2.x systems can get the same type of information utilizing the system accounts and NATS messages themselves. Those connections can be secured since they are just NATS connections. For HTTP monitoring we suggest placing behind something like NGINX for auth.
