### ISSUE TITLE
Nats streaming - Cant see subject name clearly 

### ISSUE THREAD

**Issue by shaiaTradair** [nats-io/nats-top#42]
Im working against nats-streaming server , Can't see the subject name on natstop table clearly,
Instead i see 3 subjects with prefix of : INBOX or STAN . 
Ex:
_INBOX.CjRaiQ9Kn5sKhGTJyeuDyb,
 _STAN.acks.CjRaiQ9Kn5sKhGTJyeuE91,
 _INBOX.CjRaiQ9Kn5sKhGTJyeuEEE

Why is that ?

**Comment by wallyqs** [comment]
Hi, yes those are the internal NATS subscriptions from NATS Streaming.
`nats-top` currently does not monitor nats-streaming subjects (those you can get them from a nats-streaming server e.g. via `curl http://127.0.0.1:8222/streaming/channelsz?subs=1`). 

```js
{
  "cluster_id": "test-cluster",
  "server_id": "kQk3mj3CmoA4T86msbjR2G",
  "offset": 0,
  "limit": 1024,
  "count": 1,
  "total": 1,
  "channels": [
    {
      "name": "foo",
      "msgs": 0,
      "bytes": 0,
      "first_seq": 0,
      "last_seq": 0,
      "subscriptions": [
        {
          "inbox": "_INBOX.4UlHGrBNo1P0SqSp3jgyCe",
          "ack_inbox": "_INBOX.kQk3mj3CmoA4T86msbjRX2",
          "is_durable": false,
          "is_offline": false,
          "max_inflight": 1024,
          "ack_wait": 30,
          "last_sent": 0,
          "pending_count": 0,
          "is_stalled": false
        }
      ]
    }
  ]
}
```
