### ISSUE TITLE
v0.3.2 release mac gives Segmentation fault: 11

### ISSUE THREAD

**Issue by jorisroling** [nats-io/nats-top#43]
v0.3.2 release mac gives Segmentation fault: 11

**Comment by jorisroling** [comment]
I'm on macSO v10.13.2 (High Sierra)

**Comment by wallyqs** [comment]
Confirmed the issue and will release a new binary.  In the meantime, `go get github.com/nats-io/nats-top` still works on High Sierra.

**Comment by Genert** [comment]
Still appears on Mac OSX Mojave.

**Comment by wallyqs** [comment]
Added new binary for mojave which should fix this: https://github.com/nats-io/nats-top/releases/download/v0.3.2/nats-top-darwin_amd64_mojave.zip
