### ISSUE TITLE
what the meanning of 127.0.01?

### ISSUE THREAD

**Issue by tuorifei** [nats-io/nats-top#44]
excuese me !
We have a cluster of Nats in  ipv6 environment. The host address  is 127.0.01:xxx. But the host address is the specific address such as 193.168.3.9:xxx when the nats is deployment in ipv4.  We also find the message can't transfer to other cluster router in ipv6. But it's ok in ipv4 with the same configure. please help!

**Comment by wallyqs** [comment]
127.0.0.1 is localhost for ipv4. NATS should work when bound to ipv6. What type of errors are you getting?

**Comment by tuorifei** [comment]
thanks very much! 
The cluster of Nats in ipv4 can work well, but there is a problem in ipv6.  The problem is the message from one gnastd server that can't forward to other server. the subscribe one can only recevie message when puber and subscriber connect the same gnastd server. what is the configure of nats cluster of ipv6?
