### ISSUE TITLE
Error starting nats-top without any options

### ISSUE THREAD

**Issue by BruceWangNo1** [nats-io/nats-top#45]
```text
nats-top: could not get stats from server: Get http://127.0.0.1:8222/varz: dial tcp 127.0.0.1:8222: connect: connection refused

usage: nats-top [-s server] [-m http_port] [-ms https_port] [-n num_connections] [-d delay_secs] [-sort by]
                [-cert FILE] [-key FILE ][-cacert FILE] [-k]

```

**Comment by BruceWangNo1** [comment]
Problem solved. I just found that I need to start "nats-server" with option "-m 8222".

**Comment by dsidirop** [comment]
An additional clarification:

- This works:

                 nats-top    -s localhost  -m 8222

The moral is that -s expects just the hostname and the port, if set, must be set only via -m

- This doesn't work (even though one would expect that nats-top would be smart enough to figure out what the intention is):

                 nats-top    -s localhost:8222

- And of course these also doesn't work:

                 nats-top    -s http://localhost
                 nats-top    -s localhost:123  -m 8222

**Comment by dixon1e** [comment]
Adding a Docker comment for future readers. 

If you start both your nats-box and the nats cluster in docker containers, AND you are using a shared network, say nats-net, then the name of the server you want to use for nats-top will be the -s parameter. 

For example, if you are using docker compose to launch the cluster, and nats-box in a separate docker container, and the beginning of the docker-compose.yml looks like this:

```
services:
  mynats01:
    image: docker.io/nats:2.10.12
    ports:
      - "4222:4222"
      - "8222:8222"

. . .
```
then execute nats-top as:

```
nats-top -s mynats01 -m 8222
```

**Comment by ripienaar** [comment]
Easier to use “nats top” :)
