### ISSUE TITLE
Support for displaying raw bytes# (no kibibytes or mebibytes)

### ISSUE THREAD

**Issue by dsidirop** [nats-io/nats-top#53]
Essentially what the subject says. This feature along with some other command line flags can help grab accurate snapshots of benchmark-results when running nats-related benchmarks from the command line:

For example benchmarks that are run automatically using docker-compose.yaml with nats, microservices and robot-framework.

**Comment by dsidirop** [comment]
PS: I have taken up on this quest considering that's it's relatively easy to tackle. I will submit a full request soon. @derekcollison

**Comment by wallyqs** [comment]
Thanks for the PR! Added this as a follow up so that you can toggle while the app is running: https://github.com/nats-io/nats-top/pull/55

**Comment by wallyqs** [comment]
Fixed via #54
