### ISSUE TITLE
New flag '-l' to set the column-separator when saving snapshot via '-o' to a file

### ISSUE THREAD

**Issue by dsidirop** [nats-io/nats-top#59]
Would it make sense to introduce an additional flag on top of '-o' which would set the column-separator in the grid? For example if we want the generated text file to be used as .csv later on it would make sense to set the separator to ",".

Currently I perform this sort of thing via a script in our of our CI tasks to make the output more presentable.

Just an idea of the top of my head ("thinking out loud") - let me know what you think @wallyqs

**Comment by wallyqs** [comment]
That sounds interesting, maybe something like a `--format csv` flag to collect the data so that it is easier to process later.

**Comment by dsidirop** [comment]
Cool - I could take up on this quest over the weekend! I hope the PR makes it in time for the upcoming new release.

**Comment by dsidirop** [comment]
Update:

While working on this feature during the weekend it came to my attention that using the comma "," as a separator for the csv-format is desirable in most but exactly all situations.

Spanish speaking people in particular prefer to use the semicolon ";" character as a separator because in spanish the "," character is used for other things.

Would it make sense then to introduce a "column-delimiter option    --delimiter X" instead of a "format-option    --format csv" option. The former would help people across a broader spectrum of regional settings.

Let me know what you think.

**Comment by dsidirop** [comment]
Any comments on this? @wallyqs

**Comment by wallyqs** [comment]
Fixed via #60

**Comment by dsidirop** [comment]
> Fixed via #60

Thanks for running point on this - deeply appreciated!
