### ISSUE TITLE
Numbers that are not bytes are under-counted when formatted

### ISSUE THREAD

**Issue by mdawar** [nats-io/nats-top#83]
The function [`Psize`](https://github.com/nats-io/nats-top/blob/b5f0bbb26d3079a33332d169adf629537f08a69a/util/toputils.go#L312) is being used to format all the number printed by `nats-top` but not all the numbers are bytes, the `Psize` function uses calculations for bytes (`1024`), these calculations will cause other numbers like message counts to be displayed under-counted especially with high numbers.

Take for example the current output from the demo server at https://demo.nats.io:8222/varz:

```sh
NATS server version 2.9.20 (uptime: 20d20h43m26s) 
Server: us-south-nats-demo
  ID:   NBEZOCAHBWFH46KO3YEL6IHPTYSTNZ5OH3U4JQ6BZVK4IXPVSULNU7JC
  Load: CPU:  0.0%  Memory: 54.1M  Slow Consumers: 9
  In:   Msgs: 972.5M  Bytes: 9.8G  Msgs/Sec: 0.0  Bytes/Sec: 0
  Out:  Msgs: 925.3K  Bytes: 276.8M  Msgs/Sec: 0.0  Bytes/Sec: 0
```

Here are the differences:

- In messages: Displayed `972.5M` (Raw number: `1019777182`), should be `1.0B`
- Out messages: Displayed `925.3K` (Raw number: `947585`), should be `947.6K`

**Comment by mdawar** [comment]
Since we're discussing these calculations, currently the number of messages and bytes per second are calculated based on the [time of the request](https://github.com/nats-io/nats-top/blob/b5f0bbb26d3079a33332d169adf629537f08a69a/util/toputils.go#L198), isn't it better to use the server time for these calculations as it's more accurate because it's the source of the message counts and bytes, so using this time makes more sense.

So swapping this line:
```go
now := time.Now()
```

With this:
```go
now := stats.Varz.Now
```

Should do it, but I did not make this change in the pull request as it changes the meaning of the field `LastPollTime`, it should now be called `lastServerTime` (maybe), also I don't know if this `Varz.Now` field is available on all the previous NATS server versions.

**Comment by wallyqs** [comment]
good point I think sounds good to change, also maybe could just add a couple of fields for LastServerTime and use that to calculate the rates but also keep track of the polling time just in case.

**Comment by mdawar** [comment]
> good point I think sounds good to change, also maybe could just add a couple of fields for LastServerTime and use that to calculate the rates but also keep track of the polling time just in case.

Also we can use `LastStats.Varz.Now` instead of a new field just for the server time, it's already there.

**Comment by wallyqs** [comment]
sounds good! That field has been there since v1.0 at least I think so fine to adopt.
